# code: language=yaml
---
# defaults file for ansible-manage-lvm
lvm_groups: []

# Defines if LVM will be managed by role
# default is false to ensure nothing is changed by accident.
manage_lvm: false

###     auto pvresize (waiting until ansible 2.10 or above as collections have new lvg with integrated pvresize)
###     waiting for new module in collection set to true or run pvresize manually on remote systems
###     https://docs.ansible.com/ansible/3/collections/community/general/lvg_module.html
###
pvresize_to_max: false